[Settings]
# ──────────────────────────────────────────────────────────────────────────
#  GTK 4.0 Settings — Rio theme
#  Location: ~/.config/gtk-4.0/settings.ini
#  Applies to: GTK4 apps (newer GNOME apps, some future Thunar versions)
# ──────────────────────────────────────────────────────────────────────────

gtk-application-prefer-dark-theme=1
gtk-font-name=JetBrainsMono Nerd Font 11
gtk-icon-theme-name=Papirus-Dark
gtk-cursor-theme-name=mycursor
gtk-cursor-theme-size=16
