preload=$HOME/.config/hypr/wallpapers/rio_static.png
preload=$HOME/.config/hypr/wallpapers/rio_static_secret.png
preload=$HOME/.config/hypr/wallpapers/black.png
wallpaper=,$HOME/.config/hypr/wallpapers/rio_static.png
fit=2
